# Generated by Django 5.0.6 on 2024-05-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0004_alter_staff_data_degree_alter_staff_data_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_data',
            name='Degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='staff_id',
            field=models.BigIntegerField(),
        ),
    ]
