# Generated by Django 5.0.6 on 2024-05-31 22:08

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0005_alter_staff_data_degree_alter_staff_data_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='username',
        ),
        migrations.AlterField(
            model_name='hod',
            name='photo',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/srikr/Desktop/face_recognition/static/images')),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dean.hod'),
        ),
    ]
