# Generated by Django 5.0.6 on 2024-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0006_remove_hod_password_remove_hod_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
