# Generated by Django 5.0.6 on 2024-05-31 22:16

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0007_alter_hod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hod',
            name='photo',
            field=models.ImageField(default=True, upload_to=pathlib.PureWindowsPath('C:/Users/srikr/Desktop/face_recognition/static/images')),
        ),
    ]
