# Generated by Django 5.0.6 on 2024-05-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0008_hod_password_alter_hod_id_alter_hod_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
