# Generated by Django 5.0.6 on 2024-05-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0009_hod_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
