# Generated by Django 5.0.6 on 2024-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0013_rename_degree_hod_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
