# Generated by Django 5.0.6 on 2024-06-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0015_rename_degree_hod_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='staff_data',
            old_name='Degree',
            new_name='degree',
        ),
    ]
