# Generated by Django 5.0.6 on 2024-06-01 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0016_rename_degree_hod_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_data',
            name='catagory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Dean.hod'),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
