# Generated by Django 5.0.6 on 2024-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0017_staff_data_catagory_alter_staff_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='staff_id',
            field=models.BigIntegerField(),
        ),
    ]
