# Generated by Django 5.0.6 on 2024-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0019_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
