# Generated by Django 5.0.6 on 2024-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0020_alter_hod_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
