# Generated by Django 5.0.6 on 2024-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0021_alter_hod_photo_alter_staff_data_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
