# Generated by Django 5.0.6 on 2024-06-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0025_rename_catagory_staff_data_hod_hod_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_data',
            old_name='HOD',
            new_name='Select',
        ),
    ]
