# Generated by Django 5.0.6 on 2024-06-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0026_rename_hod_staff_data_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
