# Generated by Django 5.0.6 on 2024-06-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0028_data_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='hod_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('confirm_pass', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff_register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff_register',
            name='staff_id',
        ),
    ]
