# Generated by Django 5.0.6 on 2024-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0029_hod_register_remove_staff_register_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod_register',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staff_register',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
