# Generated by Django 5.0.6 on 2024-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0030_alter_hod_register_email_alter_staff_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('confirm_pass', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
