# Generated by Django 5.0.6 on 2024-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0031_student_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
