# Generated by Django 5.0.6 on 2024-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0032_alter_staff_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='github',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hod',
            name='linkedin',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hod',
            name='whatsapp',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff_data',
            name='github',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff_data',
            name='linkedin',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff_data',
            name='whatsapp',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
