# Generated by Django 5.0.6 on 2024-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0033_hod_github_hod_linkedin_hod_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hod',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
