# Generated by Django 5.0.6 on 2024-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0034_alter_hod_github_alter_hod_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
