# Generated by Django 5.0.6 on 2024-06-10 17:23

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0035_attendance_dept_data_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100, null=True)),
                ('staff_id', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('confirm_pass', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/srikr/Desktop/face_recognition/static/images'))),
            ],
        ),
    ]
