# Generated by Django 5.0.6 on 2024-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dean', '0036_admin_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
